steps:
- name: step1
  containerRun:
    image: busybox
    script: "echo 'Hello world!'"

- name: step2
  containerRun:
    image: busybox
    script: |
      echo "step 2"
      echo "work, work, work"
      env
